### ISSUE TITLE
custom data is not showing.........

### ISSUE THREAD

**Issue by KSANTHOSHKUMA** [Jamaks/ng-fullcalendar-demo#1]
I have created a project with ng-fullcalendar, and i have write code in service as below

```
import { Inject, Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/of';
@Injectable()
export class EventSesrvice {
    public getEvents(): Observable<any> {
        const dateObj = new Date();
        const yearMonth = dateObj.getUTCFullYear() + '-' + (dateObj.getUTCMonth() + 1);
        let data: any = [{
           DoctorsCount: 5,
           TotalAppointments: 20,
           Booked: 10,
           Cancelled: 2
        },
        {
            title: 'Long Event',
            start: yearMonth + '-07',
            end: yearMonth + '-10'
        },
 ];
        return Observable.of(data);
    }
};
```

Your "Long Event" is showing in calendar in but i am unable to show 0 index data.
how to show customized data.

**if you have any youtube tutorial please provide link, thank you very much**

**Comment by Jamaks** [comment]
version ng-fullcalendar?

**Comment by KSANTHOSHKUMA** [comment]
Hi Jamaks Waiting for you reply from 2 days.. are you there??????????

**Comment by Jamaks** [comment]
Sorry, I do not have enough time for the project.

'how to show customized data.' - i understand you/

Please see oficcial site https://fullcalendar.io
and see basic demo
 https://fullcalendar.io/releases/fullcalendar/3.9.0/demos/basic-views.html

**Comment by KSANTHOSHKUMA** [comment]
Thanks @Jamaks
